POST http://localhost:6000/products
Content-Type: application/json

{
    "nameProduct":"nasi padang",
    "categories":"Makanan",
    "madeIn":"Madiun"
}
###
DELETE http://localhost:6000/products/63c16a8124a11fc0dc1a5915
###

PATCH http://localhost:6000/products/63c16b0f24a11fc0dc1a591a
Content-Type: application/json

{
    "madeIn":"Semarang"
}

###
GET http://localhost:6000/products/